### ISSUE TITLE
Add laptop device

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/systemsinventory#19]
Move laptop specific settings out of PC. Update should copy copy PC devices into laptop.

**Comment by Stardog** [comment]
Secondary MAC
Docking Stand

**Comment by tylercraig9332** [comment]
@Stardog Hey, would you like laptop to be a entirely separate device or is it okay if I handle it in a similar way with how the server device is handled (That being through a check box under the PC tab rather than a new tab). I was thinking it would be a lot easier to implement while also being more user-friendly (so users don't use PC accidentally when they should use laptop).
